server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: api-recipe
          uri: lb://api-recipe
          predicates:
            - Path=/api-recipe/**
        - id: api-socket-io
          uri: lb://api-socket-io
          predicates:
            - Path=/api-socket-io/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      datasource:
        url: jdbc:postgresql://localhost:5432/auth
        username: user
        password: user
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
          ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: health,info
        basePath: /actuator

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/