spring:
  application:
    name: api-recipe
  liquibase:
    contexts: dev
    changeLog: classpath:db/changelog/master.xml

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-host:http://localhost:8761/eureka/}