name: Pipeline Tests;

on: push
jobs:
  backend-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Backend Recipe Test/Build
        working-directory: ./app/continuous integration
        run: docker build -f Dockerfile.Junit .
