name: Pipeline Tests;

on: push
jobs:
  backend-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Backend Recipe Test/Build
        run: ./continuous integration/docker build -f Dockerfile.Junit .
